spring:
  datasource:
    url: jdbc:postgresql://cb4l59cdg4fg1k.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com:5432/d2p7tt2qf3g1q6
    username: u43lp5hefprggt
    password: p9f4639227abc3c8dabf7be0ea8691cc74a48ff43077b6b3d44398661fd1443ee
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
        show_sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect