spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_chat_app_test
    username: postgres
    password: 6468949808
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
        show_sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect