spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chat_app
    username: postgres
    password: 6468949808
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
        show_sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: carellihoula10@gmail.com
    password: xbyxfhvxklhujrdf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

application:
  security:
    jwt:
      SECRET_KEY: fdbb01bba114cb31a25c8cb9ad915723a8f19d85da8ef4526738c0be0381ae31
      expiration: 3600000
      refreshToken:
        expiration: 604800000  #seven days

